// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUNGgCrc0DAoijMlVVH704qLRcRAk_O3g',
    appId: '1:32815617682:web:b037b15de5a9b754d6784b',
    messagingSenderId: '32815617682',
    projectId: 'e-commerce-dc0c3',
    authDomain: 'e-commerce-dc0c3.firebaseapp.com',
    storageBucket: 'e-commerce-dc0c3.firebasestorage.app',
    measurementId: 'G-50524CH332',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdsLznNwKuargpi3e1HzWyMLvDb1aFXnA',
    appId: '1:32815617682:android:aa085b8ccc107d1bd6784b',
    messagingSenderId: '32815617682',
    projectId: 'e-commerce-dc0c3',
    storageBucket: 'e-commerce-dc0c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVm7ShNCAFv71AWryaB6KhuJT7c1gSfOI',
    appId: '1:32815617682:ios:29a5a9d518454572d6784b',
    messagingSenderId: '32815617682',
    projectId: 'e-commerce-dc0c3',
    storageBucket: 'e-commerce-dc0c3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVm7ShNCAFv71AWryaB6KhuJT7c1gSfOI',
    appId: '1:32815617682:ios:29a5a9d518454572d6784b',
    messagingSenderId: '32815617682',
    projectId: 'e-commerce-dc0c3',
    storageBucket: 'e-commerce-dc0c3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUNGgCrc0DAoijMlVVH704qLRcRAk_O3g',
    appId: '1:32815617682:web:008856db584c4c0fd6784b',
    messagingSenderId: '32815617682',
    projectId: 'e-commerce-dc0c3',
    authDomain: 'e-commerce-dc0c3.firebaseapp.com',
    storageBucket: 'e-commerce-dc0c3.firebasestorage.app',
    measurementId: 'G-T06MZL9QYG',
  );
}
